### ISSUE TITLE
Gencyber content todo

### ISSUE THREAD

**Issue by MLHale** [MLHale/GenCyber-web-content#6]
- [x] Pulls #5 #4 need to have first principle overviews added to them.
- [x] Needs to be tested
- [x] Checkpointed code at https://github.com/MLHale/gencyberdjango/ needs to be confirmed for accuracy
- [x] Checkpointed code at https://github.com/MLHale/gencyberember/ needs to be confirmed for accuracy
- [x] Checkpointed code at https://github.com/gencybertest/gencyberdjango/ needs to be confirmed for accuracy
- [x] I need to go over Robin's modules
- [x] Teacher modules need to be created from checkpointed code

**Comment by MLHale** [comment]
Checking off todo's updated 11pm 7/16.

Item 1 is in progress.

**Comment by MLHale** [comment]
Item 1 done ~11:45 7/16
